server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.245.224:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: 1234567
    username: root
  jpa:
    show-sql: true







