server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: Kaikai9233.
    username: root
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  file:   ./logs/cms.log








